name: superhtml
description: HTML Language Server & Templating Language Library
homepage: https://github.com/kristoff-it/superhtml
licenses:
  - MIT
languages:
  - HTML
  - SuperHTML
categories:
  - LSP
  - Formatter

source:
  # renovate:datasource=github-tags
  id: pkg:github/EliSauder/superhtml#f1e37166c51ba5a973381f5eea6aa3e49c0e67ce
  build:
    - target: unix
      run: |
        zig build
      bin: zig-out/bin/superhtml
    - target: win
      run: |
        zig build
      bin: zig-out/bin/superhtml.exe

bin:
  superhtml: "{{source.build.bin}}"
